version: '3'
services:

  wombat:
    image: erlangsolutions/wombatoam:3.8.9
    hostname: wombat
    container_name: wombat
    ports:
      - 8080:8080
    volumes:
      - ./log:/wombat/log
      - ./wombat.config:/wombat/_build/default/rel/wombat/files/wombat.config
      - ./etop:/wombat/_build/default/rel/wombat/etop
    environment:
      - WOMBAT_NODENAME='wombat@0.0.0.0'
      - CLUSTER_NODES=erlang
      - CLUSTER_COOKIE=secretcookie
      - DEFAULT_PASSWORD_FOR_ADMIN=goodpassword
      - WOMBAT_LICENSE=y4qf8j/Uynry5V24XnEXBqNTM8iUOXF2KartROQ11S0AOh2XiIMrGCPDb+7OJgothIqMgmshj8cMsHw5IMDZnRqJtBXKV8kF7XbP+8/iRqVsFcrweJw3TlvTcXbw6ZTnL3YWa0HxZKYmAOZYNYtTMifZMl+W+SBzMJ5yHZJzwZkJ33y07ZysLPrtZEClv8HDh1IpuXEZccyCp7iBDzYbmuZgk5m4utE1w9kUMVH+9ao358BEHWfswVB8izsL7xU5PIGTDA1IL6Z8Ko4rhbMDvBt7r+uJ6U0wa26FeNKkGNcKU4awG/njOu1JwrcEens1/CMJfOcZ3RhWiSEpdEUGHYNQAAABBXjaRY9LDsIwDESj8lX5SKxYsDF3YYMEZ4hMbRGXNkFJoHBhzkFSQOys8ZvRTKOUGpkBqTE/ruKfpjCDk1KTFxY4/5+bNnHLg1RsA8MXTa5FixbPTNo64mAKLLHM6OL40eGjJ3IqQUcv2JAaRn/jTK33AaKRAAj9C+7sgzib+VUjla48Y0yCJoz8bzPL5u0uadAZtimDofl26zBAb2PqZ+UYoYuada49YdTkapft5W+MUP0GtJRPUg==
  
  
  rmq1:
    image: ${RMQ_IMAGE}
    hostname: rmq1.${RMQ_HOST}
    container_name: rmq1.${RMQ_HOST}
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
    volumes:
      - ./:/workdir
      - ./erlang-cookie:/root/.erlang.cookie
      - ./erlang-cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq-env.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./collectd.conf:/etc/collectd/collectd.conf.d/graphite.conf
    # command: bash -c "/workdir/startscript.sh"
    environment:
      - RABBITMQ_USE_LONGNAME=true
      - NODENAME=rabbit@rmq1.${RMQ_HOST}
    cap_add:
      - NET_ADMIN
      - NET_RAW

  erlang:
    image: erlang
    command: bash -c "export IP=$$(hostname -I | awk '{print $$1}') && erl -name erlang@$$IP -setcookie secretcookie -noshell"

  mim1:
    image: mongooseim/mongooseim:4.2.0
    hostname: mongooseim-1
    container_name: mongooseim-1
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "9100:9100"

  phoenix:  
    image: dali32/phoenix
    command: iex --name app@phoenix.${RMQ_HOST} --cookie a -S mix phoenix.server
    hostname: phoenix.${RMQ_HOST}
    container_name: phoenix.${RMQ_HOST}
    environment:
      - PORT=4000
    ports:
      - "4000:4000"


  grafana:
    image: kamon/grafana_graphite
    container_name: grafana.${RMQ_HOST}
    hostname: grafana.${RMQ_HOST}
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "9510:80" # grafana
      - "9511:81" # graphite
      - "2003:2003" # carbon
      - "8129:8125" # statsd
      - "3000:3000"
      - "8124:8126" # statsd admin

  prometheus:
    image: prom/prometheus
    hostname: prometheus.${RMQ_HOST}
    container_name: prometheus.${RMQ_HOST}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    ports:
      - "9090:9090"


