version: '3'
services:

  wombat:
    image: erlangsolutions/wombatoam:3.8.8
    hostname: wombat
    container_name: wombat
    ports:
      - 8080:8080
    volumes:
      - ./log:/wombat/log
      - ./wombat.config:/wombat/_build/default/rel/wombat/files/wombat.config
      - ./etop:/wombat/_build/default/rel/wombat/etop
    environment:
      - WOMBAT_NODENAME='wombat@0.0.0.0'
      - CLUSTER_NODES=erlang
      - CLUSTER_COOKIE=secretcookie
      - DEFAULT_PASSWORD_FOR_ADMIN=goodpassword
      - WOMBAT_LICENSE=auenKEmfZgmb3S5SPey31Rrf1UVApjXjVajtlav74sH3HuAJYOh2dLEZTlg2jCCSk37Xjw96ae/2YnRZ83AYNAEf0NrFVYVYcAS04X+upu6Zy/kJiT+ED6dqba1s2ONu8mbrYf1Ch7VNsys+dQq5sHIMjhuTodyV7HOqZ58t1Vrgd5Gd+m8NGZLdGwbbQzfnaio6NAC2sU3wbPUoXJgzfi2+HEV5lt8xLLP+6Br2WXnsR8mAo6IoyL2xeQ8ORM7f521gGw0XMknAmT3UC1eFJQSgJKEMrXoV+kI5PR29T7P5C88zEpe3nsG1k+q1JpfuZtGftAu8oRGLTreBgexsPoNQAAABB3jaNY9bCgIxDEWLMr4VBEG/JO7FH0HXUOI02minI03xsWBdh+2M/oWbc0KuU0oVtmtUj543Di/bsd2jUv0PDnHxH0dYVImb7bkkLwQ/NFnTCj2eyWhfGxLbwTWuMzo9tDm0eSIHLDoGRmdUcUInlLHlTiBaFkBodnCnIFz7LMwdl7oMhDEF2mCk9p03jnGV5c02ZfCw5NMNAvd77oECjUam6ZXPsLmqCYnT7CMFjy77o38dNpcvd3BQSA==
  
  rmq1:
    image: ${RMQ_IMAGE}
    hostname: rmq1.${RMQ_HOST}
    container_name: rmq1.${RMQ_HOST}
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
    volumes:
      - ./:/workdir
      - ./erlang-cookie:/root/.erlang.cookie
      - ./erlang-cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq-env.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./collectd.conf:/etc/collectd/collectd.conf.d/graphite.conf
    # command: bash -c "/workdir/startscript.sh"
    environment:
      - RABBITMQ_USE_LONGNAME=true
      - NODENAME=rabbit@rmq1.${RMQ_HOST}
    cap_add:
      - NET_ADMIN
      - NET_RAW

  erlang:
    image: erlang
    command: bash -c "export IP=$$(hostname -I | awk '{print $$1}') && erl -name erlang@$$IP -setcookie secretcookie -noshell"

  mim1:
    image: mongooseim/mongooseim:5.0.0
    hostname: mongooseim-1
    container_name: mongooseim-1
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "9100:9100"

  grafana:
    image: kamon/grafana_graphite
    container_name: grafana.${RMQ_HOST}
    hostname: grafana.${RMQ_HOST}
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "9510:80" # grafana
      - "9511:81" # graphite
      - "2003:2003" # carbon
      - "8129:8125" # statsd
      - "3000:3000"
      - "8124:8126" # statsd admin

  prometheus:
    image: prom/prometheus
    hostname: prometheus.${RMQ_HOST}
    container_name: prometheus.${RMQ_HOST}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    ports:
      - "9090:9090"


